In [ ]:
import pandas as pd 
import numpy as np 
from scipy.optimize import root 

from grid_model import GridDataClass, GridModel

In [ ]:
grid_data = GridDataClass("grid_data4.xlsx", f_nom=50)
grid_model = GridModel(grid_data) 

func = grid_model._setup_pf()

BranchDataClass(S_base_mva=40, V_base_kV=132, r_l=0.002, x_l=0.011832159566199232, g_1=0.0, b_1=0.0, g_2=0.0, b_2=0.0)


In [6]:
grid_data.get_Y_bus()

array([[ 13.888889-82.16778j, -13.888889+82.16778j],
       [-13.888889+82.16778j,  13.888889-82.16778j]], dtype=complex64)

In [7]:
sol = grid_model._calc_pf()
sol = grid_model._get_pf_sol(sol) 
sol

P_calc = [-5.998  6.   ] MW 
Q_calc = [ 1.02  -1.009] Mvar 
V_buses = [1. 1.] pu 
d_buses = [0.     0.1046] deg 

In [8]:
sol.P_calc 

array([-5.99814914,  6.        ])

In [9]:
sol.Q_calc 

array([ 1.01950359, -1.00855376])

In [6]:
sol.d_buses*180/np.pi 

array([0.        , 0.52258113])

In [5]:
grid_data._create_y_bus() 

array([[ 1.452-1.936j, -1.452+1.936j],
       [-1.452+1.936j,  1.452-1.936j]], dtype=complex64)

In [14]:
(np.array([0, 1]) == np.zeros(2)).all() 

False

In [17]:
np.array([0.0, 1.0, 2.0, 3.0]).astype(int)

array([0, 1, 2, 3])

In [9]:
grid_data.get_PQ_mask() 

(array([0, 1]), array([0, 1]))

In [11]:
a = np.array([0,1,2,3,4,5])
a[np.array([0,1,0,1,0,1])]

array([0, 1, 0, 1, 0, 1])

In [5]:
V1_base = 10
S1_base = 100 

V2_base = 100 
S2_base = 150

Z1_base = V1_base**2/S1_base 
Z2_base = V2_base**2/S2_base 

In [6]:
Z = 10 # ohm 

In [7]:
Z_1 = Z/Z1_base 
Z_2 = Z/Z2_base 

In [8]:
Z_1 

10.0

In [9]:
Z_2 

0.15

In [13]:
Z_1 * (V1_base/V2_base)**2 * S2_base/S1_base 

0.15000000000000002

In [14]:
def convert_base(Z, S_new, V_new, S_old, V_old): 
    return Z * (V_old/V_new)**2 * S_new/S_old 

In [15]:
convert_base(Z_1, S2_base, V2_base, S1_base, V1_base) 

0.15000000000000002

In [17]:
Z_1 * Z1_base/Z2_base

0.15