In [1]:
import pandas as pd 
import numpy as np 
from scipy.optimize import root 

from grid_model import GridDataClass, GridModel

In [2]:
grid_data = GridDataClass("grid_data5.xlsx", f_nom=50)
grid_model = GridModel(grid_data) 

func = grid_model._setup_pf()

In [3]:
grid_data.get_Y_bus()

array([[ 27.501389-162.70041j, -28.054167+165.97069j],
       [-28.054167+165.97069j,  28.618055-169.3067j ]], dtype=complex64)

In [4]:
sol = grid_model._calc_pf()
sol = grid_model._get_pf_sol(sol) 
sol

P_calc = [ 10.006 -10.   ] MW 
Q_calc = [ 5.038 -5.   ] Mvar 
V_buses = [1.     0.9783] pu 
d_buses = [ 0.    -0.157] deg 

In [5]:
sol.P_calc 

array([ 10.00632782, -10.        ])

In [6]:
sol.Q_calc 

array([ 5.03754046, -5.        ])

In [7]:
sol.d_buses*180/np.pi 

array([ 0.        , -0.15703369])

In [8]:
sol.V_buses

array([1.        , 0.97832889])

In [9]:
# Solutions: 
V = [1.0000, 0.98809]
Q = [5.0377999, 5.0]
P = [10.0063894, 10]
delta = [0.0, -0.15860]

In [16]:
I_E_hv = I_E*I_base_hv 
I_E_lv = I_E*I_base_lv 

In [24]:
S_E = I_E 
Q_E = np.sqrt((S_E**2 - P_Fe**2)) 

In [27]:
B_mu * (22/132)**2 

0.001388888888888889