In [1]:
import pandas as pd 
import numpy as np 
from scipy.optimize import root, LinearConstraint
import matplotlib.pyplot as plt 

from simplepower.models import GridModel, ORPDHandler, GridDataClass, FileType

In [7]:
grid_data = GridDataClass("simplepower//models//grid_model_data//IEEE 14-bus RAW.txt", FileType.IEEE, f_nom=50, S_base_mva=100)
grid_model = GridModel(grid_data) 

V_lim_min = [0.9, 0.9, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]
V_lim_max = [1.1, 1.1, 1.05, 1.05, 1.05, 1.05, 1.05, 1.05, 1.05, 1.05, 1.05, 1.05, 1.05, 1.05]

# opf_model = ORPDHandler(grid_model, [0, 1, 2, 3, 4], I_lim_mat=grid_data.I_lims_pu.to_numpy())
opf_model = ORPDHandler(grid_model, [0, 1, 2, 3, 4], V_min=V_lim_min, V_max=V_lim_max)
pf_sol = grid_model.powerflow()
pf_sol.get_sol_df()

P_inj MW    Q_inj_Mvar  V_bus_pu  delta_bus_deg
0   2.324010e+02 -1.628808e+01  1.060000       0.000000
1   1.830000e+01  3.124411e+01  1.045000      -4.980866
2  -9.420000e+01  6.166090e+00  1.010000     -12.717189
3  -4.780000e+01  3.900000e+00  1.017525     -10.295506
4  -7.600000e+00 -1.600000e+00  1.018966      -8.778556
5  -1.120000e+01  3.543696e+00  1.070000     -13.659270
6  -1.005103e-07 -3.898126e-10  1.060940     -13.086670
7  -1.665335e-14  1.798234e+01  1.090000     -13.086670
8  -2.950000e+01 -1.660000e+01  1.055126     -14.599968
9  -9.000000e+00 -5.800000e+00  1.050268     -14.719552
10 -3.500000e+00 -1.800000e+00  1.056488     -14.322085
11 -6.100000e+00 -1.600000e+00  1.055162     -14.529943
12 -1.350000e+01 -5.800000e+00  1.050216     -14.626042
13 -1.490000e+01 -5.000000e+00  1.034981     -15.612820

In [8]:
pf_sol.get_P_losses()/100

0.13401042180612366

In [9]:
V_init = grid_data._grid_gens["v_set_pu"].values 
V_init 

array([1.06 , 1.045, 1.01 , 1.07 , 1.09 ])

In [10]:
opf_sol = opf_model.solve_ORPD()
opf_sol.x 

array([1.1       , 1.07826798, 1.04149032, 1.05      , 1.05      ])

In [11]:
opf_sol.fun

12.856575478586867

In [12]:
V_opt = opf_sol.x 
opf_model.set_opt_v(opf_sol) 
grid_model.powerflow().get_sol_df() 

P_inj MW    Q_inj_Mvar  V_bus_pu  delta_bus_deg
0   2.318566e+02  7.061219e+00  1.100000       0.000000
1   1.830000e+01  3.832324e+01  1.078268      -4.549728
2  -9.420000e+01  1.300740e+01  1.041490     -11.866601
3  -4.780000e+01  3.900000e+00  1.034341      -9.327748
4  -7.600000e+00 -1.600000e+00  1.036567      -7.876242
5  -1.120000e+01 -1.830079e+01  1.050000     -12.662621
6   2.245371e-07 -4.051653e-08  1.049159     -12.154752
7  -2.866631e-14  5.011974e-01  1.050000     -12.154752
8  -2.950000e+01 -1.660000e+01  1.045089     -13.727775
9  -9.000000e+00 -5.800000e+00  1.038391     -13.838889
10 -3.500000e+00 -1.800000e+00  1.040582     -13.395270
11 -6.100000e+00 -1.600000e+00  1.035633     -13.565779
12 -1.350000e+01 -5.800000e+00  1.031334     -13.681295
13 -1.490000e+01 -5.000000e+00  1.020834     -14.738722

# 30-bus system

In [30]:
grid_data = GridDataClass("simplepower//models//grid_model_data//IEEE 30-bus RAW.txt", FileType.IEEE, f_nom=50, S_base_mva=100)
grid_model = GridModel(grid_data) 

opf_model = ORPDHandler(grid_model, [0, 1, 2, 3, 4, 5], V_min=0.9, V_max=1.1)
pf_sol = grid_model.powerflow()
print(pf_sol.get_P_losses())
V_init = pf_sol.V_buses[[0, 1, 4, 7, 10, 12]]
pf_sol.get_sol_df()

17.555571827029333


P_inj MW    Q_inj_Mvar  V_bus_pu  delta_bus_deg
0   2.609556e+02 -2.023098e+01  1.060000       0.000000
1   1.830000e+01  4.352282e+01  1.045000      -5.375115
2  -2.400000e+00 -1.200000e+00  1.020894      -7.535253
3  -7.600000e+00 -1.600000e+00  1.011953      -9.287980
4  -9.420000e+01  1.664599e+01  1.010000     -14.136818
5  -2.391379e-08 -1.000359e-08  1.010652     -11.034173
6  -2.280000e+01 -1.090000e+01  1.002613     -12.835091
7  -3.000000e+01  6.035369e+00  1.010000     -11.775160
8   1.523479e-09 -2.561031e-08  1.051011     -13.810747
9  -5.800000e+00 -2.000000e+00  1.045404     -15.327868
10 -1.942890e-14  1.612035e+01  1.082000     -13.810747
11 -1.120000e+01 -7.500000e+00  1.058813     -14.379187
12 -2.949030e-14  9.323301e+00  1.071000     -14.379187
13 -6.200000e+00 -1.600000e+00  1.043893     -15.294182
14 -8.200000e+00 -2.500000e+00  1.039020     -15.409120
15 -3.500000e+00 -1.800000e+00  1.045334     -15.040861
16 -9.000000e+00 -5.800000e+00  1.040433     -15.454670
17 -3.200000e+00 -9.000000e-01  1.029115     -16.073516
18 -9.500000e+00 -3.400000e+00  1.026394     -16.277768
19 -2.200000e+00 -7.000000e-01  1.030359     -16.097664
20 -1.750000e+01 -1.120000e+01  1.033092     -15.765050
21 -1.132567e-09  1.709004e-09  1.033650     -15.749163
22 -3.200000e+00 -1.600000e+00  1.028285     -15.849816
23 -8.700000e+00 -6.700000e+00  1.022382     -16.095169
24  3.812017e-10  9.524303e-12  1.018297     -15.715457
25 -3.500000e+00 -2.300000e+00  1.000637     -16.134309
26 -9.692552e-09  1.868057e-08  1.024311     -15.221286
27 -1.159423e-08  9.555463e-09  1.007129     -11.651052
28 -2.400000e+00 -9.000000e-01  1.004495     -16.448627
29 -1.060000e+01 -1.900000e+00  0.993034     -17.329525

In [31]:
opf_model.const(V_init) 

array([1.06      , 1.045     , 1.02089377, 1.01195332, 1.01      ,
       1.01065175, 1.00261296, 1.01      , 1.05101079, 1.04540429,
       1.082     , 1.05881268, 1.071     , 1.04389278, 1.03902034,
       1.04533402, 1.04043297, 1.029115  , 1.0263944 , 1.03035897,
       1.03309182, 1.03365003, 1.02828456, 1.02238203, 1.01829733,
       1.00063736, 1.0243112 , 1.00712863, 1.00449503, 0.99303356])

In [32]:
opf_sol = opf_model.solve_ORPD()
print(opf_sol.fun)
V_opt = opf_sol.x 
opf_model.set_opt_v(opf_sol) 
grid_model.powerflow().get_sol_df() 

16.156830521210424


P_inj MW    Q_inj_Mvar  V_bus_pu  delta_bus_deg
0   2.595568e+02 -1.849241e+01  1.100000       0.000000
1   1.830000e+01  3.405597e+01  1.083890      -4.935566
2  -2.400000e+00 -1.200000e+00  1.062704      -6.965477
3  -7.600000e+00 -1.600000e+00  1.053910      -8.578637
4  -9.420000e+01  1.505389e+01  1.051370     -13.034503
5  -9.247546e-08 -1.438520e-07  1.054455     -10.218369
6  -2.280000e+01 -1.090000e+01  1.045848     -11.861345
7  -3.000000e+01  1.953156e+01  1.058491     -10.970951
8   2.974734e-08 -3.299833e-08  1.086026     -12.777593
9  -5.800000e+00 -2.000000e+00  1.083899     -14.184805
10  8.673617e-15  7.389873e+00  1.100000     -12.777593
11 -1.120000e+01 -7.499999e+00  1.095484     -13.281079
12 -2.428613e-15  3.547959e+00  1.100000     -13.281079
13 -6.200000e+00 -1.600000e+00  1.081423     -14.135672
14 -8.200000e+00 -2.500000e+00  1.077036     -14.250632
15 -3.500000e+00 -1.800000e+00  1.083052     -13.909158
16 -9.000000e+00 -5.800000e+00  1.078866     -14.299238
17 -3.200000e+00 -9.000000e-01  1.067747     -14.871846
18 -9.500000e+00 -3.400000e+00  1.065275     -15.063617
19 -2.200000e+00 -7.000000e-01  1.069173     -14.897509
20 -1.750000e+01 -1.120000e+01  1.072327     -14.592647
21  7.910846e-09 -4.386025e-09  1.072956     -14.578529
22 -3.200000e+00 -1.600000e+00  1.067675     -14.671890
23 -8.700000e+00 -6.700000e+00  1.063297     -14.914690
24 -1.032196e-08  7.949226e-09  1.061961     -14.577415
25 -3.500000e+00 -2.300000e+00  1.045054     -14.961976
26  8.267690e-08 -4.762528e-09  1.069315     -14.128275
27  4.220012e-08 -2.480358e-08  1.051987     -10.804151
28 -2.400000e+00 -9.000000e-01  1.050417     -15.252601
29 -1.060000e+01 -1.900000e+00  1.039484     -16.057396

In [33]:
opf_sol

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 16.156830521210424
       x: [ 1.100e+00  1.084e+00  1.051e+00  1.058e+00  1.100e+00
            1.100e+00]
     nit: 9
     jac: [-2.936e+01 -1.725e-02 -1.103e-03 -2.310e-03 -1.727e+00
           -2.434e+00]
    nfev: 122
    njev: 9